[package]
name = "aquatic_udp_protocol"
version = "0.2.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "UDP BitTorrent tracker protocol"
repository = "https://github.com/greatest-ape/aquatic"
keywords = ["udp", "protocol", "peer-to-peer", "torrent", "bittorrent"]
readme = "../README.md"

[dependencies]
byteorder = "1"
either = "1"
arbitrary = { version = "1", optional = true }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

[features]
default = []
arbitrary = ["arbitrary/derive"]
